name: Format and Lint Code

on:
  - push
  - pull_request

jobs:
  format:
    name: Format Code (isort)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: isort/isort-action@v1
        with:
          requirements-files: "requirements.txt"
          options: "--profile black"

  lint:
    name: Lint Code (Black)
    runs-on: ubuntu-latest
    needs: format
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
